apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: gitops-backend
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gitops-backend
  template:
    metadata:
      labels:
        app: gitops-backend
    spec:
      containers:
        - name: backend
          image: nguyenmen/gitops-backend:v1.20260611073552
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: ERROR_RATE
              value: "0.5"
            - name: VERSION
              value: "v4"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
  strategy:
    canary:
      steps:
        - setWeight: 25
        - analysis:
            templates:
            - templateName: error-rate-check
        - pause: {duration: 10s} 
