apiVersion: v1
kind: Service
metadata:
  name: gitops-backend
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: gitops-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081
  type: NodePort
