apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        alertmanager:
          config:
            global:
              smtp_smarthost: 'smtp.gmail.com:587'
              smtp_from: 'nguyenthimen190504@gmail.com'
              smtp_auth_username: 'nguyenthimen190504@gmail.com'
              smtp_auth_password: 'ezxglxslybqqslxg'
              smtp_require_tls: true
            route:
              receiver: 'my-email'
              group_by: ['alertname']
            receivers:
            - name: 'null'
            - name: 'my-email'
              email_configs:
              - to: 'nguyenthimen190504@gmail.com'
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
