apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-web
  template:
    metadata:
      labels:
        app: gitops-web
    spec:
      containers:
        - name: web
          image: nguyenmen/gitops-web:v1.20260609071100
          ports:
            - containerPort: 80
